### PR TITLE
Live Queries

### LINKED ISSUE #316: Dashboard auto-refresh lead to heavy query loads on backend
**What happened**:
Heavy query requests were sent to backend when auto-refresh set in dashboard. (This was originally submitted as discussion in https://github.com/grafana/falconlogscale-datasource/discussions/309)

Currently the query going through FalconLogScale datasource plugin are submitted as static query, and in a real environment, user often set the time-range in dashboard, and enable auto-refresh, this can impose very high load on LogScale backend, since the auto-refresh will trigger the entire query resubmitted, with different time range(e.g: 30s refresh will shift the start and end time by 30s), this is considered a brand new query in LogScale backend. We are seeing backend query job grow exponentially when just a small set of users are using Grafana dashboard with some panels have LogScale panel with auto-refresh enabled. 

Falcon LogScale do support live query, it does so by breaking down a query to historical query portion and live streaming portion, when historical query part complete, the query only need to get the events from ingest queue with new data coming in. Ideally it would be much efficient to leverage that if auto-refresh is enabled(at least when a small interval is set).
I would assume supporting that might be a complicate change and it could take time to implement, so alternatively, it would be nice to simply add an option in datasource config to ignore dashboard auto-refresh setting, and with an indicator in the panel so  user's aware the auto-refresh is disable for the panel that's using that specific data source?

**What you expected to happen**:
Handle repeated queries more efficiently, or, allow data source be configured to ignore dashboard auto-refresh setting.

**How to reproduce it (as minimally and precisely as possible)**:

**Screenshots**

**Anything else we need to know?**:

**Environment**:

- Grafana version:
- Plugin version:
- OS Grafana is installed on:
- User OS & Browser:
- Others:

### PR DESCRIPTION
**Pull request by alyssabull**
This PR implements [Humio live search](https://library.humio.com/logscale-api/api-search-live.html) and Grafana live querying to reduce backend load by fetching only new data after the initial query. These changes resolve the issue of excessive backend query jobs caused by treating each auto-refresh as a new query, significantly improving performance in environments with frequent refreshes.

Live querying can be used in both Explore mode and Dashboards.
Closes #316

### CODE REVIEW

File: pkg/humio/client.go [hunk 1]
```diff
@@ -237,27 +242,41 @@ func (c *Client) GetStream(method string, path string, query Query, ch chan Stre
...
 		res.Body.Close()
 	}()
+
 	d := json.NewDecoder(res.Body)
 
-	// note from andrew: it might be a good idea to set up a ticker to not endlessly loop over this code
-	// you should look to see if this is done with the decoder already
-	// currently this never ends unless there is an error. there should be an ending condition for this loop
-	// maybe a timeout similar to the client timeout. or maybe we can check to see if the client is timed out. not sure
+	// Set up ticker to prevent infinite loop
```
Comment (bossinc) [inline pkg/humio/client.go:262]: Its still an infinite loop. When i experimented with adding a ticker, it felt slow to get data back because it would get like 20 logs and then wait a second and get 20 more logs but that's probably fine as long as its returning all current (live) logs

File: src/components/QueryEditor/QueryEditor.tsx [hunk 2]
```diff
@@ -50,6 +64,17 @@ export function QueryEditor(props: Props) {
       ) : (
         ''
       )}
+      <div style={{padding: '5px 0 0 0'}}>
+        <EditorRow>
+          <EditorField label="Enable live querying">
```
Comment (bossinc) [inline src/components/QueryEditor/QueryEditor.tsx:69]: why are we doing this now instead of using grafana's built in button?

Comment (bossinc) [reply src/components/QueryEditor/QueryEditor.tsx:69]: also im sure this was already discussed. feel free to ignore me :D

**Comment by bossinc** [comment]
Strange things happen when running a live query using the github demo repo. its like data is being deleted and sometimes it comes back.

File: pkg/humio/client.go [hunk 3]
```diff
@@ -132,16 +137,29 @@ func NewClient(config Config, httpOpts httpclient.Options) (*Client, error) {
...
+	client.StreamingClient, err = newStreamingClient(streamingOpts)
+	if err != nil {
+		return nil, err
+	}
+
 	return client, nil
 }
 
+func newStreamingClient(opts httpclient.Options) (*http.Client, error) {
+
```
Comment (aangelisc) [inline pkg/humio/client.go:155]:
```suggestion
```

File: pkg/humio/client.go [hunk 4]
```diff
@@ -196,3 +214,74 @@ func (c *Client) Fetch(method string, path string, body *bytes.Buffer, out inter
...
+	}
+
+	req, err := http.NewRequest(method, url, &buf)
+	if err != nil {
+		return err
+	}
+	req = c.addAuthHeaders(req)
+
+	// Create a context with a timeout to avoid endless streaming
+	ctx, cancel := context.WithTimeout(context.Background(), 200*time.Second)
```
Comment (aangelisc) [inline pkg/humio/client.go:247]: I don't think this works as expected. I ran a live query that didn't stop until I cancelled it (I left it running for over 5 minutes). 

- Is there a reason we want this?
- If we do, should we make this configurable?

File: pkg/humio/client.go [hunk 5]
```diff
@@ -196,3 +214,74 @@ func (c *Client) Fetch(method string, path string, body *bytes.Buffer, out inter
...
+	defer cancel()
+
+	req = req.WithContext(ctx)
+
+	res, err := c.StreamingClient.Do(req)
+	if err != nil {
+		return err
+	}
+	defer func() {
+		res.Body.Close()
```
Comment (aangelisc) [inline pkg/humio/client.go:257]:
```suggestion
		if err = res.Body.Close(); err != nil {
		    log.DefaultLogger.Warn("failed to close response body", "error", err)
		}
```

File: pkg/humio/client.go [hunk 6]
```diff
@@ -196,3 +214,74 @@ func (c *Client) Fetch(method string, path string, body *bytes.Buffer, out inter
...
+	}()
+
+	d := json.NewDecoder(res.Body)
+
+	ticker := time.NewTicker(1 * time.Second)
```
Comment (aangelisc) [inline pkg/humio/client.go:262]: More of a curiosity question - why have we chosen 1 second? Just an arbitrary choice? Again, potentially something that could be configurable?

File: pkg/humio/client_test.go [hunk 7]
```diff
@@ -92,6 +92,23 @@ func TestClient(t *testing.T) {
 		_, err := testClient.ListRepos()
 		require.Nil(t, err)
 	})
+
+	//remove this test. its not a good functional test
```
Comment (aangelisc) [inline pkg/humio/client_test.go:96]: What was the goal of this test and can we look at re-implementing if it's essential?

File: pkg/plugin/streaming.go [hunk 8]
```diff
@@ -0,0 +1,174 @@
...
+	}
+
+	qr.Start = queryStartTime
+	c := make(chan humio.StreamingResults)
+	prev := data.FrameJSONCache{}
+	done := make(chan any)
+
+	h.QueryRunner.RunChannel(ctx, qr, c, done)
+
+	for {
```
Comment (aangelisc) [inline pkg/plugin/streaming.go:136]: I'd like to understand in a multi-tenant world, how does this logic guarantee that two different streams won't receive each others data? Is this based on the sender?

File: pkg/humio/client.go (hunk 6 above)
Comment (alyssabull) [reply pkg/humio/client.go:263]: Yes - arbitrary choice and something we could make configurable.

File: pkg/humio/client_test.go (hunk 7 above)
Comment (alyssabull) [reply pkg/humio/client_test.go:96]: This was a test that @bossinc commented out - I can revisit it.

File: pkg/plugin/streaming.go (hunk 8 above)
Comment (alyssabull) [reply pkg/plugin/streaming.go:136]: This is a great question - the logic that keeps streams isolated is `req.Path` which uniquely identifies each stream and relates it to tenant-specific query details from `req.Data`. It uses the cache to store data from each strem separately and then locks it, so multiple actions don’t conflict.

File: src/LanguageProvider.ts [hunk 9]
```diff
@@ -21,6 +21,7 @@ export default class FalconLogScaleLanguageProvider extends LanguageProvider {
       queryType: LogScaleQueryType.LQL,
       formatAs: FormatAs.Logs,
       refId: abstractQuery.refId,
+      version: '',
```
[the remark this answers is not in the document]
Comment (alyssabull) [reply src/LanguageProvider.ts:24]: There was a weird failing test but it should be fixed now.
